name: Build and Package Mac App

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Build Mac App
      run: |
        pyinstaller --onefile --windowed GPRO.py

    - name: Create App Directory
      run: |
        mkdir -p MyApp.app/Contents/MacOS
        mkdir -p MyApp.app/Contents/Frameworks
        mkdir -p MyApp.app/Contents/Resources

    - name: Package App
      run: |
        cp dist/MyApp MyApp.app/Contents/MacOS/
        cp -r /Library/Frameworks/Tk.framework /Library/Frameworks/Tcl.framework MyApp.app/Contents/Frameworks/
        cp MyApp.icns MyApp.app/Contents/Resources/
        echo "APPL????" > MyApp.app/Contents/PkgInfo

    - name: Create DMG
      run: |
        hdiutil create -volname MyApp -srcfolder MyApp.app -ov -format UDZO MyApp.dmg
