name: Build macOS app

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Remove old build files
        run: rm -rf dist/*

      - name: Build macOS app
        run: pyinstaller --name=GPRO --windowed --onefile --add-data='assets:assets' GPRO.py
        working-directory: ${{ github.workspace }}/src

      - name: Create DMG
        run: |
          hdiutil create -srcfolder dist/GPRO.app -volname "GPRO" -fs HFS+ -fsargs "-c c=64,a=16,e=16" -format UDRW -size 100m GPRO.dmg
          hdiutil convert GPRO.dmg -format UDZO -imagekey zlib-level=9 -o GPRO-macOS.dmg
        working-directory: ${{ github.workspace }}/dist

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: GPRO-macOS
          path: |
            GPRO-macOS.dmg
